#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "auth.pb.h"

namespace Auth
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void AuthRegister(RegisterRequest *request, RegisterResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void AuthLogin(LoginRequest *request, LoginResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using AuthRegisterDone = std::function<void (RegisterResponse *, srpc::RPCContext *)>;
using AuthLoginDone = std::function<void (LoginResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void AuthRegister(const RegisterRequest *req, AuthRegisterDone done);
	void AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_AuthRegister(const RegisterRequest *req);

	void AuthLogin(const LoginRequest *req, AuthLoginDone done);
	void AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_AuthLogin(const LoginRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_AuthRegister_task(AuthRegisterDone done);
	srpc::SRPCClientTask *create_AuthLogin_task(AuthLoginDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void AuthRegister(const RegisterRequest *req, AuthRegisterDone done);
	void AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_AuthRegister(const RegisterRequest *req);

	void AuthLogin(const LoginRequest *req, AuthLoginDone done);
	void AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_AuthLogin(const LoginRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_AuthRegister_task(AuthRegisterDone done);
	srpc::SRPCHttpClientTask *create_AuthLogin_task(AuthLoginDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void AuthRegister(const RegisterRequest *req, AuthRegisterDone done);
	void AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_AuthRegister(const RegisterRequest *req);

	void AuthLogin(const LoginRequest *req, AuthLoginDone done);
	void AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_AuthLogin(const LoginRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_AuthRegister_task(AuthRegisterDone done);
	srpc::BRPCClientTask *create_AuthLogin_task(AuthLoginDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void AuthRegister(const RegisterRequest *req, AuthRegisterDone done);
	void AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_AuthRegister(const RegisterRequest *req);

	void AuthLogin(const LoginRequest *req, AuthLoginDone done);
	void AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_AuthLogin(const LoginRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_AuthRegister_task(AuthRegisterDone done);
	srpc::TRPCClientTask *create_AuthLogin_task(AuthLoginDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void AuthRegister(const RegisterRequest *req, AuthRegisterDone done);
	void AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_AuthRegister(const RegisterRequest *req);

	void AuthLogin(const LoginRequest *req, AuthLoginDone done);
	void AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_AuthLogin(const LoginRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_AuthRegister_task(AuthRegisterDone done);
	srpc::TRPCHttpClientTask *create_AuthLogin_task(AuthLoginDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("Auth")
{
	this->srpc::RPCService::add_method("AuthRegister",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::AuthRegister);
		});

	this->srpc::RPCService::add_method("AuthLogin",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::AuthLogin);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::AuthRegister(const RegisterRequest *req, AuthRegisterDone done)
{
	auto *task = this->create_rpc_client_task("AuthRegister", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthRegister(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> SRPCClient::async_AuthRegister(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("AuthRegister", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::AuthLogin(const LoginRequest *req, AuthLoginDone done)
{
	auto *task = this->create_rpc_client_task("AuthLogin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthLogin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> SRPCClient::async_AuthLogin(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("AuthLogin", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_AuthRegister_task(AuthRegisterDone done)
{
	return this->create_rpc_client_task("AuthRegister", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_AuthLogin_task(AuthLoginDone done)
{
	return this->create_rpc_client_task("AuthLogin", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::AuthRegister(const RegisterRequest *req, AuthRegisterDone done)
{
	auto *task = this->create_rpc_client_task("AuthRegister", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthRegister(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_AuthRegister(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("AuthRegister", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::AuthLogin(const LoginRequest *req, AuthLoginDone done)
{
	auto *task = this->create_rpc_client_task("AuthLogin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthLogin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_AuthLogin(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("AuthLogin", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_AuthRegister_task(AuthRegisterDone done)
{
	return this->create_rpc_client_task("AuthRegister", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_AuthLogin_task(AuthLoginDone done)
{
	return this->create_rpc_client_task("AuthLogin", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::AuthRegister(const RegisterRequest *req, AuthRegisterDone done)
{
	auto *task = this->create_rpc_client_task("AuthRegister", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthRegister(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> BRPCClient::async_AuthRegister(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("AuthRegister", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::AuthLogin(const LoginRequest *req, AuthLoginDone done)
{
	auto *task = this->create_rpc_client_task("AuthLogin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthLogin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> BRPCClient::async_AuthLogin(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("AuthLogin", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_AuthRegister_task(AuthRegisterDone done)
{
	return this->create_rpc_client_task("AuthRegister", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_AuthLogin_task(AuthLoginDone done)
{
	return this->create_rpc_client_task("AuthLogin", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::AuthRegister(const RegisterRequest *req, AuthRegisterDone done)
{
	auto *task = this->create_rpc_client_task("/Auth/AuthRegister", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthRegister(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> TRPCClient::async_AuthRegister(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("/Auth/AuthRegister", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::AuthLogin(const LoginRequest *req, AuthLoginDone done)
{
	auto *task = this->create_rpc_client_task("/Auth/AuthLogin", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthLogin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> TRPCClient::async_AuthLogin(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("/Auth/AuthLogin", srpc::RPCAsyncFutureCallback<LoginResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_AuthRegister_task(AuthRegisterDone done)
{
	auto *task = this->create_rpc_client_task("/Auth/AuthRegister", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_AuthLogin_task(AuthLoginDone done)
{
	auto *task = this->create_rpc_client_task("/Auth/AuthLogin", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::AuthRegister(const RegisterRequest *req, AuthRegisterDone done)
{
	auto *task = this->create_rpc_client_task("AuthRegister", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::AuthRegister(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthRegister(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_AuthRegister(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("AuthRegister", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::AuthLogin(const LoginRequest *req, AuthLoginDone done)
{
	auto *task = this->create_rpc_client_task("AuthLogin", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::AuthLogin(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_AuthLogin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_AuthLogin(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("AuthLogin", srpc::RPCAsyncFutureCallback<LoginResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_AuthRegister_task(AuthRegisterDone done)
{
	auto *task = this->create_rpc_client_task("AuthRegister", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_AuthLogin_task(AuthLoginDone done)
{
	auto *task = this->create_rpc_client_task("AuthLogin", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace Auth

